---
- hosts: ec2
  become: yes
  tasks:
    - name: Instalar pacotes básicos
      yum:
        name:
          - docker
          - python3-pip
        state: present

    - name: Instalar módulo Docker do Python
      pip:
        name: docker
        executable: pip3
        extra_args: "--ignore-installed"

    - name: Habilitar e iniciar o serviço Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Criar diretório do projeto
      file:
        path: /opt/lab
        state: directory

    - name: Copiar Dockerfile e código da aplicação
      copy:
        src: "{{ playbook_dir }}/../docker/"
        dest: /opt/lab/
        owner: root
        group: root
        mode: 0755

    - name: Copiar o arquivo .env para o diretório da aplicação
      copy:
        src: "{{ playbook_dir }}/.env"
        dest: /opt/lab
        owner: root
        group: root
        mode: 0755

    - name: Build da imagem Docker
      community.docker.docker_image:
        name: narwhal-jupyter-lab
        build:
          path: /opt/lab
        source: build
        force_source: true

    - name: Rodar o container
      community.docker.docker_container:
        name: narwhal-jupyter-container
        image: narwhal-jupyter-lab
        state: started
        recreate: true
        ports:
          - "8888:8888"
        volumes:
          - /mnt/data:/mnt/data
